version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: unidesk_db
    restart: always
    environment:
      POSTGRES_USER: unidesk_user
      POSTGRES_PASSWORD: unidesk_pass
      POSTGRES_DB: unidesk_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: